// Curated seed content so the site has real, unique data from day one
// (needed for AdSense approval — no lorem ipsum, no placeholders).
// URLs point at well-known free online tools.

export const categories = [
  { name: 'PDF Tools',        icon: '📄', sort_order: 1,  description: 'Convert, compress, merge, split and edit PDF files online for free.' },
  { name: 'Image Tools',      icon: '🖼️', sort_order: 2,  description: 'Compress, resize, convert and edit images right in your browser.' },
  { name: 'Converters',       icon: '🔄', sort_order: 3,  description: 'Convert files, units, and currencies between hundreds of formats.' },
  { name: 'Text Tools',       icon: '✍️', sort_order: 4,  description: 'Count words, compare text, change case and clean up your writing.' },
  { name: 'Calculators',      icon: '🧮', sort_order: 5,  description: 'Free calculators for math, finance, health and everyday problems.' },
  { name: 'Developer Tools',  icon: '💻', sort_order: 6,  description: 'Format JSON, test regex, encode data and other coding helpers.' },
  { name: 'SEO & Marketing',  icon: '📈', sort_order: 7,  description: 'Research keywords, audit pages and grow your organic traffic.' },
  { name: 'Security & Privacy', icon: '🔒', sort_order: 8, description: 'Check breaches, generate passwords and keep your data safe.' },
  { name: 'Productivity',     icon: '⚡', sort_order: 9,  description: 'Shorten links, generate QR codes and get more done, faster.' },
  { name: 'Color & Design',   icon: '🎨', sort_order: 10, description: 'Build color palettes, pick fonts and find free design assets.' },
];

// category = the category `name` above.
export const tools = [
  // ── PDF Tools ──
  { name: 'PDF to JPG Converter', category: 'PDF Tools', url: 'https://www.ilovepdf.com/pdf_to_jpg', featured: true,
    tags: ['pdf', 'jpg', 'image', 'convert'],
    description: 'Convert each page of a PDF into a high-quality JPG image, or extract all embedded images. Free, no signup, works in the browser.' },
  { name: 'Compress PDF', category: 'PDF Tools', url: 'https://smallpdf.com/compress-pdf',
    tags: ['pdf', 'compress', 'reduce size'],
    description: 'Shrink the file size of a PDF while keeping it readable — perfect for email attachments and uploads with size limits.' },
  { name: 'Merge PDF', category: 'PDF Tools', url: 'https://www.ilovepdf.com/merge_pdf',
    tags: ['pdf', 'merge', 'combine'],
    description: 'Combine multiple PDF files into a single document in the order you want. Drag, drop, reorder and download.' },
  { name: 'PDF to Word', category: 'PDF Tools', url: 'https://www.pdf2go.com/pdf-to-word',
    tags: ['pdf', 'word', 'docx', 'convert'],
    description: 'Turn a PDF into an editable Microsoft Word (.docx) document while preserving layout, text and images.' },
  { name: 'Edit PDF', category: 'PDF Tools', url: 'https://www.sejda.com/pdf-editor',
    tags: ['pdf', 'edit', 'annotate'],
    description: 'Add text, shapes, images, links and annotations to a PDF and rearrange pages — no desktop software required.' },

  // ── Image Tools ──
  { name: 'Image Compressor', category: 'Image Tools', url: 'https://tinypng.com', featured: true,
    tags: ['image', 'compress', 'png', 'jpg', 'optimize'],
    description: 'Smart lossy compression for PNG and JPG images that dramatically cuts file size with almost no visible quality loss.' },
  { name: 'Background Remover', category: 'Image Tools', url: 'https://www.remove.bg', featured: true,
    tags: ['image', 'background', 'remove', 'transparent', 'ai'],
    description: 'Automatically remove the background from any photo in seconds using AI, and download a clean transparent PNG.' },
  { name: 'Image Optimizer', category: 'Image Tools', url: 'https://squoosh.app',
    tags: ['image', 'optimize', 'webp', 'avif'],
    description: 'Compare image formats and quality side by side, then export smaller WebP, AVIF or JPEG files — all offline in your browser.' },
  { name: 'Online Photo Editor', category: 'Image Tools', url: 'https://www.photopea.com',
    tags: ['image', 'editor', 'photoshop', 'psd'],
    description: 'A free, full-featured photo editor that opens PSD files and works much like Photoshop — right in your browser.' },
  { name: 'Resize Image', category: 'Image Tools', url: 'https://www.iloveimg.com/resize-image',
    tags: ['image', 'resize', 'dimensions'],
    description: 'Change the width and height of images in bulk by pixels or percentage while keeping the aspect ratio.' },

  // ── Converters ──
  { name: 'File Converter', category: 'Converters', url: 'https://cloudconvert.com', featured: true,
    tags: ['convert', 'file', 'format'],
    description: 'Convert between 200+ formats — documents, images, audio, video, ebooks and more — from a single online tool.' },
  { name: 'Any File Converter', category: 'Converters', url: 'https://convertio.co',
    tags: ['convert', 'file', 'format'],
    description: 'Drag any file in and pick the format you need. Supports hundreds of conversions with no software to install.' },
  { name: 'Unit Converter', category: 'Converters', url: 'https://www.unitconverters.net',
    tags: ['unit', 'convert', 'measurement', 'metric'],
    description: 'Convert length, weight, temperature, area, speed, data and dozens of other units instantly.' },
  { name: 'Currency Converter', category: 'Converters', url: 'https://www.xe.com/currencyconverter/',
    tags: ['currency', 'money', 'exchange rate', 'convert'],
    description: 'Convert between world currencies using live mid-market exchange rates, with historical charts.' },
  { name: 'Online Convert', category: 'Converters', url: 'https://www.online-convert.com',
    tags: ['convert', 'audio', 'video', 'document'],
    description: 'A large collection of free format converters for audio, video, image, document and archive files.' },

  // ── Text Tools ──
  { name: 'Word Counter', category: 'Text Tools', url: 'https://wordcounter.net', featured: true,
    tags: ['text', 'word count', 'character count', 'writing'],
    description: 'Count words and characters as you type, plus reading time, keyword density and sentence stats.' },
  { name: 'Text Diff Checker', category: 'Text Tools', url: 'https://www.diffchecker.com',
    tags: ['text', 'diff', 'compare'],
    description: 'Paste two blocks of text and instantly highlight every added, removed and changed line between them.' },
  { name: 'Case Converter', category: 'Text Tools', url: 'https://convertcase.net',
    tags: ['text', 'uppercase', 'lowercase', 'title case'],
    description: 'Switch text between UPPERCASE, lowercase, Title Case, Sentence case and more with one click.' },
  { name: 'Lorem Ipsum Generator', category: 'Text Tools', url: 'https://www.lipsum.com',
    tags: ['text', 'placeholder', 'lorem ipsum', 'dummy text'],
    description: 'Generate classic Lorem Ipsum placeholder text by paragraphs, words or bytes for your mockups.' },
  { name: 'Remove Duplicate Lines', category: 'Text Tools', url: 'https://www.textfixer.com/tools/remove-duplicate-lines.php',
    tags: ['text', 'duplicate', 'clean', 'list'],
    description: 'Clean up a list by removing duplicate lines and optionally sorting the result alphabetically.' },

  // ── Calculators ──
  { name: 'All-Purpose Calculator', category: 'Calculators', url: 'https://www.calculator.net', featured: true,
    tags: ['calculator', 'math', 'finance', 'health'],
    description: 'Hundreds of free calculators for finance, fitness, math, health and everyday questions in one place.' },
  { name: 'Omni Calculator', category: 'Calculators', url: 'https://www.omnicalculator.com',
    tags: ['calculator', 'science', 'everyday'],
    description: 'Over 3,000 well-explained calculators covering physics, finance, health, statistics and daily life.' },
  { name: 'Percentage Calculator', category: 'Calculators', url: 'https://www.calculator.net/percent-calculator.html',
    tags: ['calculator', 'percentage', 'percent'],
    description: 'Work out percentages, percentage change and “X is what percent of Y” without touching a formula.' },
  { name: 'Graphing Calculator', category: 'Calculators', url: 'https://www.desmos.com/calculator',
    tags: ['calculator', 'graph', 'math', 'functions'],
    description: 'Plot functions, add sliders, mark points and explore math visually with a fast online graphing calculator.' },
  { name: 'Scientific Calculator', category: 'Calculators', url: 'https://www.rapidtables.com/calc/math/Scientific_Calculator.html',
    tags: ['calculator', 'scientific', 'math'],
    description: 'A full scientific calculator with trigonometry, logarithms, powers and memory functions.' },

  // ── Developer Tools ──
  { name: 'JSON Formatter', category: 'Developer Tools', url: 'https://jsonformatter.org', featured: true,
    tags: ['json', 'format', 'validate', 'developer'],
    description: 'Beautify, validate and minify JSON, and spot syntax errors with a clear tree view of your data.' },
  { name: 'Regex Tester', category: 'Developer Tools', url: 'https://regex101.com',
    tags: ['regex', 'regular expression', 'test', 'developer'],
    description: 'Build and debug regular expressions with live match highlighting and a full explanation of every token.' },
  { name: 'Base64 Encode / Decode', category: 'Developer Tools', url: 'https://www.base64encode.org',
    tags: ['base64', 'encode', 'decode', 'developer'],
    description: 'Encode text or files to Base64 and decode Base64 back to plain text, safely in the browser.' },
  { name: 'Code Beautifier', category: 'Developer Tools', url: 'https://codebeautify.org',
    tags: ['code', 'format', 'beautify', 'developer'],
    description: 'Format and validate JSON, XML, HTML, CSS, SQL and more, plus a big grab-bag of developer utilities.' },
  { name: 'Online Code Playground', category: 'Developer Tools', url: 'https://jsfiddle.net',
    tags: ['code', 'html', 'css', 'javascript', 'playground'],
    description: 'Write and run HTML, CSS and JavaScript together and share the result with a link.' },

  // ── SEO & Marketing ──
  { name: 'Keyword Research', category: 'SEO & Marketing', url: 'https://neilpatel.com/ubersuggest/', featured: true,
    tags: ['seo', 'keywords', 'research', 'traffic'],
    description: 'Find keyword ideas, search volume and competition data to plan content that ranks and drives traffic.' },
  { name: 'Question Research', category: 'SEO & Marketing', url: 'https://answerthepublic.com',
    tags: ['seo', 'questions', 'content ideas'],
    description: 'Discover the real questions people ask around any topic to fuel your blog and FAQ content.' },
  { name: 'Google Trends', category: 'SEO & Marketing', url: 'https://trends.google.com',
    tags: ['seo', 'trends', 'search interest'],
    description: 'Compare how search interest for topics rises and falls over time and across regions.' },
  { name: 'Meta Tags Preview', category: 'SEO & Marketing', url: 'https://metatags.io',
    tags: ['seo', 'meta tags', 'open graph', 'preview'],
    description: 'Generate and preview how your page looks when shared on Google, Twitter, Facebook and Slack.' },
  { name: 'Search Console', category: 'SEO & Marketing', url: 'https://search.google.com/search-console',
    tags: ['seo', 'google', 'indexing', 'analytics'],
    description: 'Monitor how Google crawls and indexes your site, submit sitemaps and track your search performance.' },

  // ── Security & Privacy ──
  { name: 'Password Generator', category: 'Security & Privacy', url: 'https://bitwarden.com/password-generator/', featured: true,
    tags: ['password', 'generator', 'security', 'random'],
    description: 'Create strong, random passwords and passphrases with adjustable length and character rules.' },
  { name: 'Have I Been Pwned', category: 'Security & Privacy', url: 'https://haveibeenpwned.com',
    tags: ['security', 'breach', 'email', 'privacy'],
    description: 'Check whether your email address or password has appeared in a known data breach.' },
  { name: 'VirusTotal', category: 'Security & Privacy', url: 'https://www.virustotal.com',
    tags: ['security', 'malware', 'scan', 'url'],
    description: 'Scan a file or URL with dozens of antivirus engines to check it for malware and threats.' },
  { name: 'SSL Server Test', category: 'Security & Privacy', url: 'https://www.ssllabs.com/ssltest/',
    tags: ['security', 'ssl', 'https', 'certificate'],
    description: 'Deep analysis of a website’s SSL/TLS configuration with an easy-to-read A–F grade.' },
  { name: 'Temporary Email', category: 'Security & Privacy', url: 'https://temp-mail.org',
    tags: ['email', 'temporary', 'privacy', 'spam'],
    description: 'Get a disposable inbox to sign up for things without handing over your real email address.' },

  // ── Productivity ──
  { name: 'URL Shortener', category: 'Productivity', url: 'https://tinyurl.com', featured: true,
    tags: ['url', 'shortener', 'link'],
    description: 'Turn long, ugly links into short, shareable URLs you can paste anywhere.' },
  { name: 'QR Code Generator', category: 'Productivity', url: 'https://www.qr-code-generator.com',
    tags: ['qr code', 'generator', 'link'],
    description: 'Create QR codes for links, text, Wi-Fi and contact details, then download them as images.' },
  { name: 'Pomodoro Timer', category: 'Productivity', url: 'https://pomofocus.io',
    tags: ['timer', 'pomodoro', 'focus', 'productivity'],
    description: 'A clean Pomodoro timer to structure focused work sessions and breaks and beat procrastination.' },
  { name: 'Online Notepad', category: 'Productivity', url: 'https://anotepad.com',
    tags: ['notes', 'notepad', 'text'],
    description: 'Jot down and auto-save quick notes in the browser without installing anything.' },
  { name: 'Screen Recorder', category: 'Productivity', url: 'https://www.loom.com',
    tags: ['screen', 'record', 'video', 'productivity'],
    description: 'Record your screen and camera and instantly share a link — great for demos and quick explainers.' },

  // ── Color & Design ──
  { name: 'Color Palette Generator', category: 'Color & Design', url: 'https://coolors.co', featured: true,
    tags: ['color', 'palette', 'design', 'hex'],
    description: 'Generate beautiful color schemes in seconds, lock the colors you like and export them for your project.' },
  { name: 'Adobe Color Wheel', category: 'Color & Design', url: 'https://color.adobe.com',
    tags: ['color', 'wheel', 'palette', 'design'],
    description: 'Build harmonious color palettes with a color wheel and extract themes from any image.' },
  { name: 'Google Fonts', category: 'Color & Design', url: 'https://fonts.google.com',
    tags: ['fonts', 'typography', 'design', 'free'],
    description: 'Browse and pair hundreds of free, open-source web fonts and grab the code to embed them.' },
  { name: 'Free Stock Photos', category: 'Color & Design', url: 'https://unsplash.com',
    tags: ['images', 'stock photos', 'free', 'design'],
    description: 'Download high-resolution photos you can use for free on personal and commercial projects.' },
  { name: 'Online Design Studio', category: 'Color & Design', url: 'https://www.canva.com',
    tags: ['design', 'graphics', 'templates', 'social media'],
    description: 'Design social posts, presentations, posters and more from thousands of drag-and-drop templates.' },
];
